blog/urls.py
from django.contrib import admin
from django.urls import path, include
#from note.views import handler, show
from django.conf.urls.static import static
from django.conf import settings
from home.views import index, MySearchView
from note.views import note_detail, category_list
from project.views import project_list, project_detail
import haystack
from home.views import get_logs
from favorites.views import show_favorites
from comments.views import post_comments

urlpatterns = [
    path('admin/', admin.site.urls),    
    path('mdeditor/', include('mdeditor.urls')),
    path('', index, name='index'),
    path('note-detail/<note_id>', note_detail, name='note_detail'),
    path('category/<cate_id>', category_list, name='category_list'),
    path('projects/', project_list, name='project_list'),
    path('projects/detail/<p_id>', project_detail, name='project_detail'),
    path('search/', MySearchView(), name='haystack_search'),
    path('logs/', get_logs, name='logs'),
    path('favorites/', show_favorites, name='favorites'),
    path('comments/<int:note_id>', post_comments, name='comments')
 
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comments/models.py
from django.db import models
from note.models import Note

class Comments(models.Model):
    nickname = models.CharField(max_length=20)
    email = models.EmailField()
    content = models.TextField(max_length=255)
    created_time = models.DateTimeField(auto_now_add=True)
    target = models.ForeignKey(Note, on_delete=models.CASCADE)

    def __str__(self):
        return self.content
    
    class Meta:
        ordering = ['-created_time']

note/models.py
from django.db import models
from django.contrib.auth.models import User
from mdeditor.fields import MDTextField
# Create your models here.

class Category(models.Model):
    category = models.CharField(max_length=20, verbose_name="分类")

    def __str__(self):
        return self.category
    
    @classmethod
    def get_all_categories(cls):
        return cls.objects.all()

class Note(models.Model):
    author = models.ForeignKey(User, verbose_name="作者", on_delete=models.DO_NOTHING)
    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING, verbose_name="分类")
    title = models.CharField(max_length=500, verbose_name="标题")
    desc = models.TextField(max_length=500, verbose_name="摘要", null=True, blank=True)
    content = MDTextField(verbose_name='文章内容')
    created_time = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")
    cover = models.ImageField(upload_to='cover', help_text='160*100')
    views = models.PositiveIntegerField(default=0, editable=True, verbose_name='阅读量')

    def __str__(self):
        return self.title
    
    #使用类方法获取所有文章，遵循数据操作尽量封装在model中的原则
    @classmethod
    def get_all_notes(cls):        
        return cls.objects.all().order_by('-id')
    
    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

note/views.py
from django.shortcuts import render
from . models import Note, Category
from django.core.paginator import Paginator
#使用markdown，将markdown格式渲染成html格式
import markdown
# Create your views here.

def note_detail(request, note_id):
    content = Note.objects.get(id=note_id)
    content.increase_views()
    content.content = markdown.markdown(content.content,
                        extensions = [
                            'markdown.extensions.extra',
                            'markdown.extensions.codehilite',
                            'markdown.extensions.toc',
                    ])
    categories = Category.get_all_categories()
    context = {
        'content': content,
        'categories': categories,
    }
    return render(request, 'note/detail.html', context)

def category_list(request, cate_id):
    notes = Category.objects.get(id=cate_id).note_set.all().order_by('-id')
    paginator = Paginator(notes, 20)
    page = request.GET.get('page')
    page_obj = paginator.get_page(page)
    categories = Category.get_all_categories()
    context = {
        'paginator': paginator,
        'page_obj': page_obj,
        'is_paginated': True,
        'categories': categories,

    }
    return render(request, 'note/list.html', context)
    

templates/note/detail.html
{% extends 'base.html' %}
{% block title %}{% endblock %}
{% block main %}
<div class="row pt-3">
    <div class="col-lg-9">
        <div class="pb-2">
            <span><img src="http://images.china.cn/attachement/jpg/site1000/20141117/0019b91ec8ef15d39b483e.jpg" alt="" width="30" height="30" class="rounded-circle"></span>
            <span>{{ content.author }}</span>
        </div>
        <h5>{{ content.title }}</h5>
        <div class="pb-2">
            <span style="font-size:12px"><img src="/static/svgs/icons/clock.svg" alt="">{{ content.created_time }}</span>
            <span style="font-size:12px"><img src="/static/svgs/icons/eye.svg" alt="">{{ content.views }}</span>

            <span style="font-size:12px"><img src="/static/svgs/icons/chat.svg" alt="">{{ comments_count }}</span>
            <a style="
            font-size: 0.5rem;
            padding: 0 .2rem;
            height: 0.7rem;
            line-height: 0.7rem;
            border-radius: .1875rem;
            color: #159963;
            background-color: #E7F4EF;" href="{% url 'category_list' content.category.id %}">{{ content.category }}</a>
        </div> 
        <hr>       
        <p>{{ content.content |safe }}</p>
        {% load comments_extra %}
        {% show_comments content %}
        {% comments_post content %}

    </div>
    {% include 'collection_bar.html'%}
</div>
{% endblock %}

templates/note/list.html
{% extends 'base.html' %}
{% block title %}首页-tabworld.cn python自学笔记{% endblock %}
{% block main %}
<!-- 文章列表页 -->
<div class="row pt-3">
    <div class="col-lg-9">
        <!-- 遍历文章 -->
        {% for note in page_obj %}
        <div class="row">
            <div class="col-md-3">
                <img src="{{ note.cover.url }}" class="ml-3 img-fluid d-sm-none d-none d-md-block" alt="..."
                    style="height: 100px; width: 160px;">
            </div>
            <div class="col-md-9">
                <h6 class="mt-0"><a href="{% url 'note_detail' note.id %}">{{ note.title }}</a></h6>
                <span class="desc mb-0">{{ note.desc }}</span>
                <div class="pb-3">
                    <span style="font-size: 12px;"><img src="/static/svgs/icons/person.svg" widht="20" height="20"
                            alt="">{{ note.author }}</span>
                    <span style="font-size: 12px;"><img src="/static/svgs/icons/clock.svg" widht="20" height="20"
                            alt="">{{ note.created_time }}</span>
                    <span style="font-size: 12px;"><img src="/static/svgs/icons/eye.svg" widht="20" height="20"
                            alt="">{{ note.views }}</span>
                    <span style="font-size: 12px;"><img src="/static/svgs/icons/chat.svg" widht="20" height="20"
                            alt="">{{ note.comments_set.count }}</span>
                    <a style="
                    font-size: 0.5rem;
                    padding: 0 .2rem;
                    height: 0.7rem;
                    line-height: 0.7rem;
                    border-radius: .1875rem;
                    color: #159963;
                    background-color: #E7F4EF;"
                        href="{% url 'category_list' note.category.id %}">{{ note.category }}</a>
                </div>
            </div>
        </div>
        <hr>
        {% empty %}
        暂无文章
        {% endfor %}
        <!-- 分页 -->
        {% if is_paginated %}
        <ul class="pagination mt-5">
            <!-- 判断是否有上一页，如果没有，上一页就不可点击 -->
            {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">上一页</a></li>
            {% else %}
            <li class="page-item disabled"><span class="page-link">上一页</span></li>
            {% endif %}

            <!-- 显示页数及判断当前在哪一页 -->
            {% for i in paginator.page_range %}
                {% if page_obj.number == i %}
                <li class="page-item active"><span class="page-link">{{ i }}<span class="sr-only">(current)</span></span></li>
                {% else %}
                <li class="page-item"><a href="?page={{ i }}" class="page-link">{{ i }}</a></li>
                {% endif %}
            {% endfor %}

            <!-- 判断是否还有下一页，如果没有，下一页不可点击 -->
            {% if page_obj.has_next %}
            <li class="page-item"><a href="?page={{ page_obj.next_page_number }}" class="page-link">下一页</a></li>
            {% else %}
            <li class="page-item disabled"><span class="page-link">下一页</span></li>
            {% endif %}
        </ul>
        {% else %}
        <p class="text-center font-weight-lighter">无更多数据了</p>
        {% endif %}
    </div>
    {% include 'collection_bar.html'%}
</div>

{% endblock %}